### PR TITLE
Job dirs in SPOOL need to be owned by the job owners (SOFTWARE-4623)

### PR DESCRIPTION
**Pull request by brianhlin**

### CODE REVIEW

**Comment by matyasselmeci** [comment]
So you want the dirs to be owned by condor:condor but not the files, is that it?

**Comment by brianhlin** [comment]
Not quite that simple. The job files are kept in subdirs in `/var/lib/condor-ce/spool`, which should be owned by the job owners. However, there are other subdirs in spool that hsould be owned by condor

**Review by matyasselmeci — APPROVED** [review]

**Comment by brianhlin** [comment]
I verified that this works with empty PVCs as well as retaining jobs across restarts! Logs seem to be stomped on, though, but that appears to be a SLATE chart bug

**Comment by edquist** [comment]
>The job files are kept in subdirs in /var/lib/condor-ce/spool, which should be owned by the job owners.
>However, there are other subdirs in spool that should be owned by condor

So, regular files excluded, are there any subdirs which should _not_ be owned by condor?

(I see `/var/lib/condor-ce/spool` in your list so apparently that directory gets owned by condor.)

Anyway if you just want to make all the directories (but not files) owned by condor, you can do it with find:

```
mkdir -p \
      /var/log/condor-ce/ \
      /var/lib/condor-ce/execute \
      /var/lib/condor-ce/spool/ceview/{metrics,vos}

find /var/{log,lib}/condor-ce -type d -exec chown condor:condor {} +
```

**Comment by edquist** [comment]
Ah, nevermind, i get it now - ok so you want /var/lib/condor-ce/spool/*/ user-owned dirs to be left alone ... Makes sense.

Though i admit now i am curious what user dirs exist at image setup time

**Comment by brianhlin** [comment]
> Though i admit now i am curious what user dirs exist at image setup time

This is to support job retention across container redeploys if the admin is storing `/var/lib/condor-ce/` on a PVC. We have to do the `mkdir` + `chown` on first deployment with a PVC since PVCs are initially empty and stomp on any existing contents from within the container.

**Comment by edquist** [comment]
Ahh, persistent volumes!  Of course!

**Pull request merged**
