### PR TITLE
Adds SSH_PROXY_JUMP_USER

### PR DESCRIPTION
**Pull request by ashtongraves**

### CODE REVIEW

**Comment by ashtongraves** [comment]
@brianhlin @JaimeFrey 

Talked about this in our standup, but we want the ability to specify a jump host user in the future (and I was going to add it to our helm and expose as env like SSH_PROXY_JUMP). Will this work?

**Comment by ashtongraves** [comment]
Helm change: https://github.com/osg-htc/helm-charts/pull/37

**Review by JaimeFrey — APPROVED** [review]
Looks good to me.

**Comment by ashtongraves** [comment]
Great can you merge? It says I need 1 approving review

**Comment by ashtongraves** [comment]
Can this be merged please @JaimeFrey @brianhlin

**Review by JaimeFrey — APPROVED** [review]
LGTM

**Review by brianhlin — APPROVED** [review]

**Pull request merged**
